name: MDWriter

options:
  bundleIdPrefix: listentotherain
  deploymentTarget:
    macOS: "14.0"

settings:
  MARKETING_VERSION: 2.2.0
  CURRENT_PROJECT_VERSION: 220
  SWIFT_VERSION: 6.0

packages:
  MDEditor:
    url: https://github.com/SteveShi/MDEditor.git
    from: 1.0.1
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle
    from: 2.9.1
  swift-markdown:
    url: https://github.com/swiftlang/swift-markdown
    from: 0.7.3
  WhatsNewKit:
    url: https://github.com/SvenTiigi/WhatsNewKit
    from: 2.2.1
  MarkdownView:
    url: https://github.com/LiYanan2004/MarkdownView
    from: 2.6.0

targets:
  MDWriter:
    type: application
    platform: macOS
    sources:
      - path: MDWriter
    resources:
      - path: MDWriter/Assets.xcassets
      - path: MDWriter/Resources
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: listentotherain.MDWriter
      INFOPLIST_FILE: MDWriter/App/Info.plist
      ENABLE_APP_SANDBOX: NO
      GENERATE_INFOPLIST_FILE: NO
    dependencies:
      - package: MDEditor
        product: MDEditor
      - package: Sparkle
        product: Sparkle
      - package: swift-markdown
        product: Markdown
      - package: WhatsNewKit
        product: WhatsNewKit
      - package: MarkdownView
        product: MarkdownView

schemes:
  MDWriter:
    build:
      targets:
        MDWriter: all
